FROM node:16.14.2-alpine as builder
WORKDIR /usr/app/frontend

COPY package.json .
RUN npm install --quiet --production

COPY . .

FROM builder

COPY --from=builder /usr/app/frontend/node_modules  ./node_modules

EXPOSE 3001
CMD ["npm", "start"]